### ISSUE TITLE
[Question]: Is this mod useable outside the gtnh modpack?

### ISSUE THREAD

**Issue by vasmark1** [GTNewHorizons/twilightforest#26]
When I tried to launch with it I've got:

`cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: twilightforest/biomes/TFBiomeBase
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
	
Is there some dependencies or it's just hardly built-in to GTNH Modpack?

**Comment by mitchej123** [comment]
Please provide a mod list and full log.

**Comment by vasmark1** [comment]
Actually it crashes even if I download a Version 2.4.3 - 1.7.10 Maintenance Update [By the GTNH Team] from Curseforge :/

**Comment by vasmark1** [comment]
Fixed by removing Grimoire-mc1.7.10-3.2.11.
