### ISSUE TITLE
ConcurrentModificationException Crash

### ISSUE THREAD

**Issue by SrYthan** [GTNewHorizons/twilightforest#74]
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1498)
	at twilightforest.world.MapGenTFHollowTree.generateStructuresInChunk(MapGenTFHollowTree.java:72)
	at twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:953)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:429)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1197)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:76)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:845)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695)
	at java.lang.Thread.run(Thread.java:748)

**Comment by N2K2021** [comment]
Version of TForest?

**Comment by SrYthan** [comment]
latest version

**Comment by SrYthan** [comment]
i made this change and works fine for me 

    public boolean generateStructuresInChunk(World world, Random rand, int chunkX, int chunkZ) {
        int mapX = (chunkX << 4) + 8;
        int mapZ = (chunkZ << 4) + 8;
        boolean flag = false;
        
        List<StructureStart> structures = new ArrayList<>(this.structureMap.values());
    
        for (StructureStart structurestart : structures) {
            if (structurestart.isSizeableStructure()
                    && structurestart.getBoundingBox().intersectsWith(mapX, mapZ, mapX + 15, mapZ + 15)) {
                structurestart
                        .generateStructure(world, rand, new StructureBoundingBox(mapX, mapZ, mapX + 15, mapZ + 15));
                flag = true;
            }
        }
    
        return flag;
    }
