### ISSUE TITLE
Server crash on TF Nagastone facing in worldgen

### ISSUE THREAD

**Issue by Delfayne** [GTNewHorizons/twilightforest#83]
Random crash in worldgen on exploring TF, very close to the world portal. First instance of triggering this simply kicks the player. If they re-login, it crashes the entire server.

GTNH 2.6.1

Seems similar to https://github.com/GTNewHorizons/twilightforest/issues/71

Crashlog snippet
```---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 7/6/24, 3:35 PM
Description: Exception getting block type in world

java.lang.NullPointerException: Cannot invoke "twilightforest.block.BlockTFNagastone2$Yaw.ordinal()" because "facing" is null
at RFB-Launch//twilightforest.block.BlockTFNagastone2.GetMetadata(BlockTFNagastone2.java:639)
at RFB-Launch//twilightforest.structures.courtyard.ComponentTFNagaCourtyardTerraceBrazier.func_74875_a(ComponentTFNagaCourtyardTerraceBrazier.java:265)
at RFB-Launch//net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
at RFB-Launch//net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
at RFB-Launch//twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:950)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
at RFB-Launch//net.minecraft.world.World.func_72964_e(World.java:419)
at RFB-Launch//net.minecraft.world.World.func_147439_a(World.java:345)
at RFB-Launch//net.minecraft.world.World.func_147437_c(World.java:365)
at RFB-Launch//mods.natura.worldgen.BaseCropWorldgen.generateBarley(BaseCropWorldgen.java:145)
at RFB-Launch//mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:53)
at RFB-Launch//cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at RFB-Launch//twilightforest.block.BlockTFNagastone2.GetMetadata(BlockTFNagastone2.java:639)
at RFB-Launch//twilightforest.structures.courtyard.ComponentTFNagaCourtyardTerraceBrazier.func_74875_a(ComponentTFNagaCourtyardTerraceBrazier.java:265)
at RFB-Launch//net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
at RFB-Launch//net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
at RFB-Launch//twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:950)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
at RFB-Launch//net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
Found chunk: true
Location: World: (-1026,158,-845), Chunk: (at 14,9,3 in -65,-53; contains blocks -1040,0,-848 to -1025,255,-833), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513)
Stacktrace:
at RFB-Launch//net.minecraft.world.World.func_147439_a(World.java:345)
at RFB-Launch//net.minecraft.world.World.func_147437_c(World.java:365)
at RFB-Launch//mods.natura.worldgen.BaseCropWorldgen.generateBarley(BaseCropWorldgen.java:145)
at RFB-Launch//mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:53)
at RFB-Launch//cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Lyfts** [comment]
Fixed in https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12
